#!/bin/bash

flex calc-lexico.l
bison -d calc-sintaxis.y
gcc -o prog lex.yy.c calc-sintaxis.tab.c ast/ast.c ast/ast_to_image.c table_of_symbols/table_symbols.c table_of_symbols/symbol_to_image.c generate_asm/generate_asm.c -lfl
