#!/bin/bash

flex calc-lexico.l
bison -d calc-sintaxis.y
# bison -v calc-sintaxis.y #para que de un output con los conflictos
# gcc lex.yy.c calc-sintaxis.tab.c
gcc -o prog lex.yy.c calc-sintaxis.tab.c ast.c ast_to_image.c -lfl # ver porque anda con este comando y no con el de arriba 
